# Generated by Django 2.2 on 2019-11-18 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0023_auto_20191108_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTvPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('overview', models.TextField()),
                ('tv', models.ManyToManyField(to='movies.Tv')),
            ],
        ),
        migrations.CreateModel(
            name='NewsFilmPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('overview', models.TextField()),
                ('film', models.ManyToManyField(to='movies.Film')),
            ],
        ),
    ]
