# Generated by Django 2.2 on 2019-11-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191118_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='publish_date',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
