# Generated by Django 2.2 on 2019-11-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newspost_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='film',
            field=models.ManyToManyField(blank=True, to='movies.Film'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='tv',
            field=models.ManyToManyField(blank=True, to='movies.Tv'),
        ),
    ]
