version: "3.3"

volumes:
  postgres_data_vol:
    external: false

services:

  postgres:
    image: postgres:latest
    ports:
      - '127.0.0.1:5432:5432'
    expose:
      - 5432
    environment:
      POSTGRES_DB: movies_db
    volumes:
      - postgres_data_vol:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

  celery:
    image: core
    command: celery -A myproject worker -l info --beat
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - type: bind
        source: ./
        target: /code/

  web:
    build: .
    image: core
    restart: always
    entrypoint: /code/entrypoint.sh

    ports:
      - 8000:8000
    env_file:
      - .env

    depends_on:
      - postgres
      - redis

    volumes:
      - type: bind
        source: ./
        target: /code/

