# Generated by Django 2.2 on 2019-11-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0003_auto_20191101_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('popularity', models.FloatField()),
                ('gender', models.IntegerField()),
                ('profile_path', models.CharField(max_length=100)),
                ('adult', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('source_id', models.IntegerField()),
                ('known_for', models.ManyToManyField(to='movies.Film')),
            ],
        ),
    ]
