# Generated by Django 2.2 on 2019-11-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20191104_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_path',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
