# Generated by Django 2.2 on 2019-11-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_auto_20191105_1322'),
        ('people', '0005_auto_20191104_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='known_for_tv',
            field=models.ManyToManyField(to='movies.Tv'),
        ),
        migrations.AlterField(
            model_name='person',
            name='adult',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='popularity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='source_id',
            field=models.IntegerField(null=True),
        ),
    ]
