# Generated by Django 2.2 on 2019-11-01 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('popularity', models.CharField(max_length=50)),
                ('vote_count', models.IntegerField()),
                ('video', models.BooleanField()),
                ('poster_path', models.CharField(max_length=100)),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.CharField(max_length=100)),
                ('original_language', models.CharField(max_length=5)),
                ('original_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('vote_average', models.FloatField()),
                ('overview', models.CharField(max_length=512)),
                ('release_date', models.CharField(max_length=50)),
                ('genre_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Genre')),
            ],
        ),
    ]
