# Generated by Django 2.2 on 2019-11-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191101_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genre_ids',
        ),
        migrations.AddField(
            model_name='film',
            name='genre_ids',
            field=models.ManyToManyField(to='movies.Genre'),
        ),
    ]
