# Generated by Django 2.2 on 2019-11-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20191104_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='popularity',
            field=models.FloatField(null=True),
        ),
    ]
