# Generated by Django 2.2 on 2019-11-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20191104_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='vote_count',
            field=models.IntegerField(null=True),
        ),
    ]
