# Generated by Django 2.2 on 2019-11-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20191104_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='popularity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='source_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='vote_count',
            field=models.IntegerField(),
        ),
    ]
