# Generated by Django 2.2 on 2019-11-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20191104_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='source_id',
            field=models.IntegerField(default=None),
        ),
    ]
