# Generated by Django 2.2 on 2019-11-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20191104_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='original_title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.CharField(default='1970-01-01', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
