# Generated by Django 2.2 on 2019-11-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20191104_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='adult',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='original_language',
            field=models.CharField(default='en-US', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='original_title',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='vote_average',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='vote_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
