# Generated by Django 2.2 on 2019-11-05 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_auto_20191105_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvGenre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tv',
            name='genre_ids',
            field=models.ManyToManyField(to='movies.TvGenre'),
        ),
    ]
