# Generated by Django 2.2 on 2019-11-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20191101_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='popularity',
            field=models.FloatField(),
        ),
    ]
