# Generated by Django 2.2 on 2019-11-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20191104_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.CharField(default='1970-01-01', max_length=50, null=True),
        ),
    ]
