# Generated by Django 2.2 on 2019-11-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20191104_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='popularity',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
