# Generated by Django 2.2 on 2019-11-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_film_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='original_language',
            field=models.CharField(default='en-US', max_length=5),
        ),
        migrations.AlterField(
            model_name='film',
            name='original_title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='overview',
            field=models.CharField(default='', max_length=5120),
        ),
        migrations.AlterField(
            model_name='film',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.CharField(default='1970-01-01', max_length=10),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='type',
            field=models.CharField(default='movie', max_length=5),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='vote_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='film',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
