# Generated by Django 2.2 on 2019-11-05 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20191105_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.IntegerField()),
                ('poster_path', models.CharField(max_length=100, null=True)),
                ('popularity', models.FloatField(null=True)),
                ('backdrop_path', models.CharField(max_length=100, null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('overview', models.CharField(max_length=5120, null=True)),
                ('first_air_date', models.CharField(max_length=10, null=True)),
                ('original_language', models.CharField(max_length=10, null=True)),
                ('vote_count', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=1000, null=True)),
                ('original_name', models.CharField(max_length=1000, null=True)),
                ('type', models.CharField(default='tv', max_length=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='backdrop_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='original_language',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='original_title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='overview',
            field=models.CharField(max_length=5120, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='popularity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='source_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='vote_average',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='vote_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='source_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
