# Generated by Django 2.2 on 2019-11-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_auto_20191105_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
